mockSubwayId = "1002"
mockRecptnDt = "2024-11-21 16:19:00"
mockUpOrdKey1 = "01004성수0"
mockUpOrdKey2 = "02005성수0"
mockDownOrdKey1 = "11001성수0"
mockDownOrdKey2 = "12006성수0"
mockBarvlDt = "60"
mockSubwayRealtimeJson = {
    "errorMessage": {
        "status": 200,
        "code": "INFO-000",
        "message": "정상 처리되었습니다.",
        "link": "",
        "developerMessage": "",
        "total": 4,
    },
    "realtimeArrivalList": [
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 1,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 선릉방면",
            "subwayHeading": None,
            "statnFid": "1002000222",
            "statnTid": "1002000220",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockUpOrdKey1,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2265",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "5분 20초 후",
            "arvlMsg3": "방배",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 2,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 선릉방면",
            "subwayHeading": None,
            "statnFid": "1002000222",
            "statnTid": "1002000220",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockUpOrdKey2,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2267",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "8분 후",
            "arvlMsg3": "사당",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 3,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 강남방면",
            "subwayHeading": None,
            "statnFid": "1002000220",
            "statnTid": "1002000222",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockDownOrdKey1,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "3262",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "전역 도착",
            "arvlMsg3": "선릉",
            "arvlCd": "5",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 4,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 강남방면",
            "subwayHeading": None,
            "statnFid": "1002000220",
            "statnTid": "1002000222",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockDownOrdKey2,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2264",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "7분 30초 후",
            "arvlMsg3": "잠실",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
    ],
}

mock_soosu = {
    "errorMessage": {
        "status": 200,
        "code": "INFO-000",
        "message": "정상 처리되었습니다.",
        "link": "",
        "developerMessage": "",
        "total": 8,
    },
    "realtimeArrivalList": [
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 1,
            "selectedCount": 8,
            "subwayId": "1075",
            "subwayNm": None,
            "updnLine": "상행",
            "trainLineNm": "왕십리행 - 선정릉방면",
            "subwayHeading": None,
            "statnFid": "1075075216",
            "statnTid": "1075075214",
            "statnId": "1075075215",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "01001왕십리0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "0",
            "btrainNo": "6070",
            "bstatnId": "1075075210",
            "bstatnNm": "왕십리",
            "recptnDt": "2025-02-05 10:44:12",
            "arvlMsg2": "전역 도착",
            "arvlMsg3": "한티",
            "arvlCd": "5",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 2,
            "selectedCount": 8,
            "subwayId": "1002",
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 삼성방면",
            "subwayHeading": None,
            "statnFid": "1002000221",
            "statnTid": "1002000219",
            "statnId": "1002000220",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "01002성수0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "150",
            "btrainNo": "2169",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": "2025-02-05 10:45:14",
            "arvlMsg2": "2분 30초 후",
            "arvlMsg3": "강남",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 3,
            "selectedCount": 8,
            "subwayId": "1002",
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 삼성방면",
            "subwayHeading": None,
            "statnFid": "1002000221",
            "statnTid": "1002000219",
            "statnId": "1002000220",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "02004성수0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "300",
            "btrainNo": "3171",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": "2025-02-05 10:45:14",
            "arvlMsg2": "5분 후",
            "arvlMsg3": "서초",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 4,
            "selectedCount": 8,
            "subwayId": "1075",
            "subwayNm": None,
            "updnLine": "상행",
            "trainLineNm": "왕십리행 - 선정릉방면",
            "subwayHeading": None,
            "statnFid": "1075075216",
            "statnTid": "1075075214",
            "statnId": "1075075215",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "02006왕십리0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "0",
            "btrainNo": "6524",
            "bstatnId": "1075075210",
            "bstatnNm": "왕십리",
            "recptnDt": "2025-02-05 10:44:12",
            "arvlMsg2": "[6]번째 전역 (수서)",
            "arvlMsg3": "수서",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 5,
            "selectedCount": 8,
            "subwayId": "1002",
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 역삼방면",
            "subwayHeading": None,
            "statnFid": "1002000219",
            "statnTid": "1002000221",
            "statnId": "1002000220",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "11002성수0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "90",
            "btrainNo": "3180",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": "2025-02-05 10:45:14",
            "arvlMsg2": "1분 30초 후",
            "arvlMsg3": "삼성",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 6,
            "selectedCount": 8,
            "subwayId": "1075",
            "subwayNm": None,
            "updnLine": "하행",
            "trainLineNm": "인천행 - 한티방면",
            "subwayHeading": None,
            "statnFid": "1075075214",
            "statnTid": "1075075216",
            "statnId": "1075075215",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "11003인천0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "0",
            "btrainNo": "6543",
            "bstatnId": "1075075271",
            "bstatnNm": "인천",
            "recptnDt": "2025-02-05 10:45:07",
            "arvlMsg2": "[3]번째 전역 (압구정로데오)",
            "arvlMsg3": "압구정로데오",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 7,
            "selectedCount": 8,
            "subwayId": "1002",
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 역삼방면",
            "subwayHeading": None,
            "statnFid": "1002000219",
            "statnTid": "1002000221",
            "statnId": "1002000220",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "12004성수0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "270",
            "btrainNo": "2182",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": "2025-02-05 10:45:14",
            "arvlMsg2": "4분 30초 후",
            "arvlMsg3": "잠실새내",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 8,
            "rowNum": 8,
            "selectedCount": 8,
            "subwayId": "1075",
            "subwayNm": None,
            "updnLine": "하행",
            "trainLineNm": "죽전행 - 한티방면",
            "subwayHeading": None,
            "statnFid": "1075075214",
            "statnTid": "1075075216",
            "statnId": "1075075215",
            "statnNm": "선릉",
            "trainCo": None,
            "trnsitCo": "2",
            "ordkey": "12005죽전0",
            "subwayList": "1002,1075",
            "statnList": "1002000220,1075075215",
            "btrainSttus": "일반",
            "barvlDt": "0",
            "btrainNo": "6095",
            "bstatnId": "1075075233",
            "bstatnNm": "죽전",
            "recptnDt": "2025-02-05 10:45:07",
            "arvlMsg2": "[5]번째 전역 (왕십리)",
            "arvlMsg3": "왕십리",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
    ],
}
