services:
  eb_database:
    image: mysql:9.0.1
    container_name: eb_database
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./eb_fast_api/env/dot_env_files/.mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -p$$MYSQL_ROOT_PASSWORD
      timeout: 30s
      retries: 10
    networks:
      - eb_server
  eb_fast_api:
    depends_on:
      eb_database:
        condition: service_healthy
    container_name: eb_fast_api
    build:
      context: .
      dockerfile: eb_fast_api.Dockerfile
    ports:
      - 2003:8000
    volumes:
      - ./eb_fast_api:/api/eb_fast_api
    networks:
      - eb_server
networks:
  eb_server:
    name: eb_server
    driver: bridge
