services:
  eb_fast_api:
    container_name: eb_fast_api
    depends_on:
      - jenkins
    build:
      context: .
      dockerfile: dockerfiles/eb_fast_api.Dockerfile
    ports:
      - 8000:8000

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8080:8080