mockSubwayId = "1002"
mockRecptnDt = "2024-11-21 16:19:00"
mockUpOrdKey1 = "01004성수0"
mockUpOrdKey2 = "02005성수0"
mockDownOrdKey1 = "11001성수0"
mockDownOrdKey2 = "12006성수0"
mockBarvlDt = "60"
mockSubwayRealtimeJson = {
    "errorMessage": {
        "status": 200,
        "code": "INFO-000",
        "message": "정상 처리되었습니다.",
        "link": "",
        "developerMessage": "",
        "total": 4,
    },
    "realtimeArrivalList": [
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 1,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 선릉방면",
            "subwayHeading": None,
            "statnFid": "1002000222",
            "statnTid": "1002000220",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockUpOrdKey1,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2265",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "5분 20초 후",
            "arvlMsg3": "방배",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 2,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "외선",
            "trainLineNm": "성수행 - 선릉방면",
            "subwayHeading": None,
            "statnFid": "1002000222",
            "statnTid": "1002000220",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockUpOrdKey2,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2267",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "8분 후",
            "arvlMsg3": "사당",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 3,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 강남방면",
            "subwayHeading": None,
            "statnFid": "1002000220",
            "statnTid": "1002000222",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockDownOrdKey1,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "3262",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "전역 도착",
            "arvlMsg3": "선릉",
            "arvlCd": "5",
            "lstcarAt": "0",
        },
        {
            "beginRow": None,
            "endRow": None,
            "curPage": None,
            "pageRow": None,
            "totalCount": 4,
            "rowNum": 4,
            "selectedCount": 4,
            "subwayId": mockSubwayId,
            "subwayNm": None,
            "updnLine": "내선",
            "trainLineNm": "성수행 - 강남방면",
            "subwayHeading": None,
            "statnFid": "1002000220",
            "statnTid": "1002000222",
            "statnId": "1002000221",
            "statnNm": "역삼",
            "trainCo": None,
            "trnsitCo": "1",
            "ordkey": mockDownOrdKey2,
            "subwayList": "1002",
            "statnList": "1002000221",
            "btrainSttus": "일반",
            "barvlDt": mockBarvlDt,
            "btrainNo": "2264",
            "bstatnId": "1002000211",
            "bstatnNm": "성수",
            "recptnDt": mockRecptnDt,
            "arvlMsg2": "7분 30초 후",
            "arvlMsg3": "잠실",
            "arvlCd": "99",
            "lstcarAt": "0",
        },
    ],
}
