path_data = {
    "time": 45,
    "type": 3,
    "payment": 1600,
    "subPaths": [
        {
            "time": 2,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "수서",
            "distance": 114,
            "stations": [],
            "way_code": None,
            "startName": "수서역 3호선",
            "transports": [],
            "start_station_id": None,
        },
        {
            "time": 16,
            "type": 1,
            "startX": "127.100909",
            "startY": "37.487924",
            "endName": "강남구청",
            "distance": 8000,
            "stations": [
                {"name": "수서"},
                {"name": "대모산입구"},
                {"name": "개포동"},
                {"name": "구룡"},
                {"name": "도곡"},
                {"name": "한티"},
                {"name": "선릉"},
                {"name": "선정릉"},
                {"name": "강남구청"},
            ],
            "way_code": 1,
            "startName": "수서",
            "transports": [
                {"busType": None, "busNumber": None, "subwayType": "수인분당선"}
            ],
            "start_station_id": 1521,
        },
        {
            "time": 0,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "강남구청",
            "distance": 0,
            "stations": [],
            "way_code": None,
            "startName": "강남구청",
            "transports": [],
            "start_station_id": None,
        },
        {
            "time": 6,
            "type": 1,
            "startX": "127.041283",
            "startY": "37.517181",
            "endName": "논현",
            "distance": 1900,
            "stations": [{"name": "강남구청"}, {"name": "학동"}, {"name": "논현"}],
            "way_code": 2,
            "startName": "강남구청",
            "transports": [{"busType": None, "busNumber": None, "subwayType": "7호선"}],
            "start_station_id": 730,
        },
        {
            "time": 3,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "신사역",
            "distance": 204,
            "stations": [],
            "way_code": None,
            "startName": "논현",
            "transports": [],
            "start_station_id": None,
        },
        {
            "time": 17,
            "type": 2,
            "startX": "127.020593",
            "startY": "37.512867",
            "endName": "한국폴리텍1대학",
            "distance": 4519,
            "stations": [
                {"name": "신사역"},
                {"name": "한남대교전망카페"},
                {"name": "순천향병원입구"},
                {"name": "한남역.용산노인종합복지관"},
                {"name": "한남동하이페리온"},
                {"name": "보광동신동아아파트"},
                {"name": "기업은행보광동지점"},
                {"name": "한국폴리텍1대학"},
            ],
            "way_code": None,
            "startName": "신사역",
            "transports": [{"busType": "간선", "busNumber": "421", "subwayType": None}],
            "start_station_id": 105884,
        },
        {
            "time": 1,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "멜로즈",
            "distance": 4,
            "stations": [],
            "way_code": None,
            "startName": "한국폴리텍1대학",
            "transports": [],
            "start_station_id": None,
        },
    ],
    "walkTime": 6,
    "busTransitCount": 1,
    "subwayTransitCount": 2,
}

# path_data = {
#     "type": 3,
#     "time": 45,
#     "walkTime": 6,
#     "payment": 1600,
#     "busTransitCount": 1,
#     "subwayTransitCount": 2,
#     "subPaths": [
#         {
#             "type": 3,
#             "time": 2,
#             "startName": "수서역 3호선",
#             "startX": "None",
#             "startY": "None",
#             "start_station_id": None,
#             "way_code": None,
#             "endName": "수서",
#             "distance": 114,
#             "transports": [],
#             "stations": [],
#         },
#         {
#             "type": 1,
#             "time": 16,
#             "startName": "수서",
#             "startX": "127.100909",
#             "startY": "37.487924",
#             "start_station_id": 1521,
#             "way_code": 1,
#             "endName": "강남구청",
#             "distance": 8000,
#             "transports": [
#                 {"subwayType": "수인분당선", "busNumber": None, "busType": None}
#             ],
#             "stations": [
#                 {"name": "수서"},
#                 {"name": "대모산입구"},
#                 {"name": "개포동"},
#                 {"name": "구룡"},
#                 {"name": "도곡"},
#                 {"name": "한티"},
#                 {"name": "선릉"},
#                 {"name": "선정릉"},
#                 {"name": "강남구청"},
#             ],
#         },
#         {
#             "type": 3,
#             "time": 0,
#             "startName": "강남구청",
#             "startX": "None",
#             "startY": "None",
#             "start_station_id": None,
#             "way_code": None,
#             "endName": "강남구청",
#             "distance": 0,
#             "transports": [],
#             "stations": [],
#         },
#         {
#             "type": 1,
#             "time": 6,
#             "startName": "강남구청",
#             "startX": "127.041283",
#             "startY": "37.517181",
#             "start_station_id": 730,
#             "way_code": 2,
#             "endName": "논현",
#             "distance": 1900,
#             "transports": [{"subwayType": "7호선", "busNumber": None, "busType": None}],
#             "stations": [{"name": "강남구청"}, {"name": "학동"}, {"name": "논현"}],
#         },
#         {
#             "type": 3,
#             "time": 3,
#             "startName": "논현",
#             "startX": "None",
#             "startY": "None",
#             "start_station_id": None,
#             "way_code": None,
#             "endName": "신사역",
#             "distance": 204,
#             "transports": [],
#             "stations": [],
#         },
#         {
#             "type": 2,
#             "time": 17,
#             "startName": "신사역",
#             "startX": "127.020593",
#             "startY": "37.512867",
#             "start_station_id": 105884,
#             "way_code": None,
#             "endName": "한국폴리텍1대학",
#             "distance": 4519,
#             "transports": [{"subwayType": None, "busNumber": "421", "busType": "간선"}],
#             "stations": [
#                 {"name": "신사역"},
#                 {"name": "한남대교전망카페"},
#                 {"name": "순천향병원입구"},
#                 {"name": "한남역.용산노인종합복지관"},
#                 {"name": "한남동하이페리온"},
#                 {"name": "보광동신동아아파트"},
#                 {"name": "기업은행보광동지점"},
#                 {"name": "한국폴리텍1대학"},
#             ],
#         },
#         {
#             "type": 3,
#             "time": 1,
#             "startName": "한국폴리텍1대학",
#             "startX": "None",
#             "startY": "None",
#             "start_station_id": None,
#             "way_code": None,
#             "endName": "멜로즈",
#             "distance": 4,
#             "transports": [],
#             "stations": [],
#         },
#     ],
# }
