path_data = {
    "time": 53,
    "type": 1,
    "payment": 1600,
    "subPaths": [
        {
            "time": 5,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "수서",
            "distance": 317,
            "stations": [],
            "startName": "수서역",
            "transports": [{"busType": None, "busNumber": "None", "subwayType": None}],
        },
        {
            "time": 33,
            "type": 1,
            "startX": "127.102147",
            "startY": "37.487473",
            "endName": "약수",
            "distance": 19100,
            "stations": [
                {"name": "수서"},
                {"name": "일원"},
                {"name": "대청"},
                {"name": "학여울"},
                {"name": "대치"},
                {"name": "도곡"},
                {"name": "매봉"},
                {"name": "양재"},
                {"name": "남부터미널"},
                {"name": "교대"},
                {"name": "고속터미널"},
                {"name": "잠원"},
                {"name": "신사"},
                {"name": "압구정"},
                {"name": "옥수"},
                {"name": "금호"},
                {"name": "약수"},
            ],
            "startName": "수서",
            "transports": [
                {"busType": None, "busNumber": "None", "subwayType": "3호선"}
            ],
        },
        {
            "time": 0,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "약수",
            "distance": 0,
            "stations": [],
            "startName": "약수",
            "transports": [{"busType": None, "busNumber": "None", "subwayType": None}],
        },
        {
            "time": 8,
            "type": 1,
            "startX": "127.010298",
            "startY": "37.554166",
            "endName": "이태원",
            "distance": 2700,
            "stations": [
                {"name": "약수"},
                {"name": "버티고개"},
                {"name": "한강진"},
                {"name": "이태원"},
            ],
            "startName": "약수",
            "transports": [
                {"busType": None, "busNumber": "None", "subwayType": "6호선"}
            ],
        },
        {
            "time": 7,
            "type": 3,
            "startX": "None",
            "startY": "None",
            "endName": "멜로즈",
            "distance": 467,
            "stations": [],
            "startName": "이태원",
            "transports": [{"busType": None, "busNumber": "None", "subwayType": None}],
        },
    ],
    "walkTime": 12,
    "busTransitCount": 0,
    "subwayTransitCount": 2,
}
