pipeline {
    agent any

    

    stages {
        stage('Test') {
            steps {
                sh "echo ${env.BRANCH_NAME}"
                sh "echo ${env.GIT_BRANCH}"
            }
        }
        // stage('Github') {
        //     when { 
        //         anyOf { 
        //             expression { env.GIT_BRANCH == 'origin/main' }
        //             expression { env.GIT_BRANCH == 'origin/develop' }
        //         } 
        //     }
        //     steps {
        //         script {
        //             if (env.Branc)
        //             git branch: 'develop', url: 'https://github.com/EARLYBUDDY-TEAM/EB-Server.git'
        //         }
        //     }
        // }
        // stage('main 브랜치 배포') {
        //     when { expression { env.GIT_BRANCH == 'origin/main' } }
        //     steps {
        //         dir('api') {
        //             sh 'sudo docker compose up -d'
        //         }
        //     }
        // }
        // stage('develop 브랜치 배포') {
        //     when { expression { env.GIT_BRANCH == 'origin/develop' } }
        //     steps {
        //         dir('api') {
        //             sh 'sudo docker compose up -d'
        //         }
        //     }
        // }
    }
}