pipeline {
    agent any

    stages {
        stage('Github') {
            when { 
                anyOf { 
                    expression { env.GIT_BRANCH == 'main' }
                    expression { env.GIT_BRANCH == 'develop' }
                } 
            }
            steps {
                git branch: env.GIT_BRANCH, 
                url: 'https://github.com/EARLYBUDDY-TEAM/EB-Server.git'
            }
            steps {
                dir('api') {
                    sh 'sudo docker compose up -d'
                }
            }
        }
    }
}