services:
  eb_fast_api_develop:
    container_name: eb_fast_api_develop
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - 8001:8001
    networks:
      - eb_server

networks:
  eb_server:
    name: eb_server
    driver: bridge