services:
  eb_fast_api_dev:
    container_name: eb_fast_api_dev
    build:
      context: .
      dockerfile: eb_fast_api.Dockerfile
    ports:
      - 8001:8001
    networks:
      - eb_server
    entrypoint: python eb_fast_api/main.py

networks:
  eb_server:
    name: eb_server
    driver: bridge