services:
  eb_fast_api_main:
    container_name: eb_fast_api_main
    build:
      context: .
      dockerfile: eb_fast_api.Dockerfile
    ports:
      - 8000:8000
    networks:
      - eb_server
    entrypoint: uvicorn --app-dir ./eb_fast_api eb_server.main:app --reload --host=0.0.0.0 --port=8000

networks:
  eb_server:
    name: eb_server
    driver: bridge