services:
  eb_fast_api_dev:
    container_name: eb_fast_api_dev
    build:
      context: .
      dockerfile: eb_fast_api.Dockerfile
    ports:
      - 8001:8001
    networks:
      - eb_server
    entrypoint: uvicorn --app-dir ./eb_fast_api eb_server.main:app --reload --host=0.0.0.0 --port=8001

networks:
  eb_server:
    name: eb_server
    driver: bridge